package com.slavakukhto.lastfm.shared.di

const val APP_MODULE = "APP_MODULE"
const val SPLASH_MODULE = "SPLASH_MODULE"
const val GENERAL_MODULE = "GENERAL_MODULE"
const val MAIN_MODULE = "MAIN_MODULE"
const val PROFILE_MODULE = "PROFILE_MODULE"
const val SCROBBLES_MODULE = "SCROBBLES_MODULE"
const val FAVOURITE_TRACKS_MODULE = "FAVOURITE_TRACKS_MODULE"
const val FAVOURITE_ALBUMS_MODULE = "FAVOURITE_ALBUMS_MODULE"
const val FAVOURITE_ARTISTS_MODULE = "FAVOURITE_ARTISTS_MODULE"
